---

- name: Configure Web Server
  hosts: ec2-webserver
  become: true
  
  tasks:
    - name: Install pip3
      apt:
        update_cache: true
        name: python3-pip

    - name: Install Docker
      apt:
        name: docker.io

    - name: Install docker python sdk
      shell: |
        pip3 install docker
        
    - name: Start Docker
      shell: |
        systemctl start docker
        systemctl enable docker
    


